---

- name: Install ntp daemon
  pacman:
    name: ntp
    state: present
  register: install
  until: install is success
  retries: 10
  delay: 2
  notify: rkhunter propupdate

- name: Configure swiss metas atomic clocks
  copy: src=ntp.conf dest=/etc/
  notify:
    - restart ntpd

- name: Make sure ntpd is stopped
  service:
    name: ntpd
    state: stopped
    enabled: yes
  when: install is changed

- name: Sync time with swiss ntp metas atomic clock
  shell: ntpdate 0.north-america.pool.ntp.org
  when: install is changed

- name: Start ntpd back up
  service:
    name: ntpd
    state: started
    enabled: yes
  when: install is changed

- name: Sync time to hwclock
  shell: hwclock --systohc
  when: install is changed
