---

- name: install i3 windowmanager and components
  pacman:
    name:
      - xorg
      - xorg-xinit
      - i3-gaps
      - i3lock
      #- i3status
      - i3status-rust
      - dmenu
      - feh
      - dunst
      - rofi
      - compton
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install thunar file manager
  pacman:
    name:
      - thunar
