---

- name: install fonts
  pacman:
    name: "{{ item }}"
    state: present
  with_items:
    - ttf-dejavu
    - ttf-liberation
    - ttf-droid
    - noto-fonts-emoji
    - fontconfig
    - xorg-font-utils
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install aur fonts using pacaur
  yay:
    name: "{{ item }}"
    user: "{{ user.name }}"
  with_items:
    - powerline-fonts-git
    - oh-my-zsh-git
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
