---

- name: install slack
  aur:
    name: slack-desktop
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  tags:
    - aur

- name: Jail slack
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/slack
        state=link
  tags:
    - firejail

# - name: install zoom
#   aur:
#     name: zoom
#     user: "{{ user.name }}"
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2
#   tags:
#     - aur


# - name: Jail zoom
#   file: src=/usr/bin/firejail
#         dest=/usr/local/bin/zoom
#         state=link
#   tags:
#     - firejail

- name: install notion-app
  aur:
    name: notion-app
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  tags:
    - aur

- name: Jail notion-app
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/notion-app
        state=link
  tags:
    - firejail


- name: install libreoffice
  pacman: name=libreoffice-fresh state=present

- name: Jail libreoffice
  file: src=/usr/bin/libreoffice
        dest=/usr/local/bin/libreoffice
        state=link
  tags:
    - firejail
