---

- name: install slack
  yay:
    name: slack-desktop
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install zoom
  yay:
    name: zoom
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install notion-app
  yay:
    name: notion-app
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
