---

- name: Install signal-desktop
  yay:
    name: signal-desktop
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Jail signal-desktop
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/signal-desktop
        state=link
  tags:
    - firejail
