---

- name: Install discord
  pacman: name=signal-desktop state=present

- name: Jail signal-desktop
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/signal-desktop
        state=link
  tags:
    - firejail

- name: Install discord
  pacman: name=discord state=present

- name: Jail discord
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/discord
        state=link
  tags:
    - firejail
