---

- name: Install spotify from aur
  yay: name=spotify user={{ user.name }}

- name: Jail spotify
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/spotify
        state=link
  tags:
    - firejail
