---

- name: install keybase
  aur:
    name: keybase-bin
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: set keybase directory
#   command:
#     cmd: "keybase config set mountdir /home/{{ user.name }}/keybase"
#     creates: /home/{{ user.name }}/keybase

- name: install gnome-screenshot
  pacman: name=gnome-screenshot state=present

- name: install filezilla
  pacman: name=filezilla state=present

- name: Jail filezilla
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/filezilla
        state=link
  tags:
    - firejail


- name: install vlc
  pacman: name=vlc state=present

- name: Jail vlc
  file: src=/usr/bin/firejail
        dest=/usr/local/bin/vlc
        state=link
  tags:
    - firejail

- name: install usbutils
  pacman: name=usbutils state=present

- name: install etcher
  aur:
    name: balena-etcher
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install polkit (for etcher)
  pacman: name=polkit state=present

- name: install polkit-gnome (for etcher)
  pacman: name=polkit-gnome state=present

- name: install unzip
  pacman: name=unzip state=present

- name: install peek (screen gif recorder)
  pacman: name=peek state=present
