---

- name: install keybase
  aur:
    name: keybase-bin
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: set keybase directory
#   command:
#     cmd: "keybase config set mountdir /home/{{ user.name }}/keybase"
#     creates: /home/{{ user.name }}/keybase

- name: install gnome-screenshot
  pacman: name=gnome-screenshot state=present

- name: install filezilla
  pacman: name=filezilla state=present

- name: install vlc
  pacman: name=vlc state=present

- name: install unzip
  pacman: name=unzip state=present

- name: install peek (screen gif recorder)
  pacman: name=peek state=present
