---

- name: Install alsa-utils and pulseaudio tools
  pacman:
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - alsa-utils
    - pulseaudio
    - pulseaudio-alsa
    - pavucontrol

# todo: create teh folder below

- name: Deploy HiFi pulse audio daemon configuration
  template:
    src: daemon.conf.j2
    dest: "/home/{{ user.name }}/.config/pulse/daemon.conf"
  become_user: "{{ user.name }}"
  become: true
