---


- name: install asdf
  yay:
    name: asdf-vm
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install jq (used to parse)
  pacman: name=jq state=present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
