---

- name: install java plugin (asdf)
  command:
    cmd: "asdf plugin add java"
    creates: /home/{{ user.name }}/.asdf/plugins/java



# - name: install java 8
#   command:
#     cmd: "asdf install java adopt-openjdk-8u252-b09"
#     creates: /home/{{ user.name }}/.asdf/installs/java/adoptopenjdk-8.0.262+10

# - name: install java 13
#   command:
#     cmd: "asdf install java adopt-openjdk-13.0.1+9"
#     creates: /home/{{ user.name }}/.asdf/installs/java/adoptopenjdk-14.0.2+12

- name: install maven
  pacman: name=maven state=present
