---

- name: install urxvt terminal emulator
  pacman:
    name: rxvt-unicode
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: install termite terminal emulator
  pacman:
    name: "{{ item }}"
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2
  with_items:
    - termite
    - termite-terminfo

- name: install kitty terminal emulator
  pacman:
    name: kitty
    state: present
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

# - name: install tmux terminal multiplexer
#   pacman:
#     name: tmux
#     state: present
#   register: task_result
#   until: task_result is success
#   retries: 10
#   delay: 2
