---

- name: install steam
  pacman: name=steam state=present

- name: install lib32-nvidia-utils
  pacman: name=lib32-nvidia-utils state=present


- name: install path of building
  aur:
    name: path-of-building-community-git
    user: "{{ user.name }}"
  register: task_result
  until: task_result is success
  retries: 10
  delay: 2

- name: Jail path-of-building
  file: src=/usr/bin/PathOfBuildingCommunity
        dest=/usr/local/bin/PathOfBuildingCommunity
        state=link
  tags:
    - path-of-building
    - firejail
